
development:
  adapter: mysql2
  database: jm_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: jm_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: jm_production
  username: root
  password: 
  encoding: utf8

